download:
  credentials_env_file: src/.env
  tiles_file: src/config/europe-dem-tiles.txt
  url_root: https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/ASTGTM.003/
  tile_filter_prefix: ASTGTMV003
  output_path: src/data/training
  parallel: false
  tile_size: 3600
  subtile_size: 225
  land_coverage_threshold: 0.5
  flow_threshold: 230
  target_size: 256
train:
  training_data_folder: src/data/training
  tile_filter_prefix: ASTGTMV003
  device_name: mps
  visualization_frequency: 20
  hyper:
    batch_size: 4
    epochs: 10
    gen_lr: 0.0005
    critic_lr: 0.0001
    betas: [0.5, 0.9]
    l1_lambda: 100
    gp_lambda: 10
    critic_iter: 5